<?php
namespace Terrific\TwigExtensionsBundle\Tests\Twig\Extension {
    use Terrific\TwigExtensionsBundle\Twig\Extension\FillerExtension;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:30:13.
     */
    class FillerExtensionTest extends \PHPUnit_Framework_TestCase
    {
        /**
         * @var FillerExtension
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
            $this->object = new FillerExtension();
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
        }

        /**
         * @covers Terrific\TwigExtensionsBundle\Twig\Extension\FillerExtension::getParagraph
         */
        public function testGetParagraph()
        {
            $this->assertTrue(strpos($this->object->getParagraphs(1), "<p>") === false);
            $this->assertTrue(strpos($this->object->getParagraphs(1, true), "<p>") !== false);
        }

        /**
         * @covers Terrific\TwigExtensionsBundle\Twig\Extension\FillerExtension::getWords
         */
        public function testGetWords()
        {
            $this->assertNotEmpty($this->object->getWords(1, false));
            $this->assertCount(1, explode(",", $this->object->getWords(1, false)));
            $this->assertTrue(preg_match('#[A-Z]#', $this->object->getWords(1, true)) === 1);
        }
    }
}
