<?php
namespace Terrific\TwigExtensionsBundle\Tests\Twig\Extension {
    use Terrific\TwigExtensionsBundle\Twig\Extension\TerrificIdentGenerator;

    /**
     * Generated by PHPUnit_SkeletonGenerator on 2012-09-08 at 09:30:13.
     */
    class TerrificIdentGeneratorTest extends \PHPUnit_Framework_TestCase
    {
        /**
         * @var TerrificIdentGenerator
         */
        protected $object;

        /**
         * Sets up the fixture, for example, opens a network connection.
         * This method is called before a test is executed.
         */
        protected function setUp()
        {
            $this->object = new TerrificIdentGenerator();
        }

        /**
         * Tears down the fixture, for example, closes a network connection.
         * This method is called after a test is executed.
         */
        protected function tearDown()
        {
        }


        /**
         * @covers Terrific\TwigExtensionsBundle\Twig\Extension\TerrificIdentGenerator::buildId
         */
        public function testBuildId()
        {
            $this->assertEquals(0, strpos($this->object->buildId("ns"), "ns"));
            $this->assertEquals(0, strpos($this->object->buildId("asdf"), "asdf"));

            $this->assertTrue(strpos($this->object->buildId("ns"), "-") !== false);

            $id = $this->object->buildId("test");
            $this->assertEquals($id, $this->object->buildId("test", true));
        }

    }
}
